### ISSUE TITLE
TimeoutError

### ISSUE THREAD

**Issue by francescocassini** [AhmedElwerdany/blogger-image#1] opened 2023-11-23 09:14 UTC
I'm trying to use the code to upload very little image towards my blog.
Anyway I receive always this message:

node_modules/puppeteer/node_modules/puppeteer-core/lib/cjs/puppeteer/common/WaitTask.js:59
                void this.terminate(new Errors_js_1.TimeoutError(`Waiting failed: ${options.timeout}ms exceeded`));
                                    ^
TimeoutError: Waiting for selector `div[data-tooltip="Insert image"]` failed: Waiting failed: 30000ms exceeded

Is it normal? I have to change waiting time? or data-tooltip is not more in the code of blogger?
Thanks

**Comment by AhmedElwerdany** [comment] 2023-11-24 22:12
can you please add `headless: false` to the option object ? and send what causes it to error ? 
maybe you get redirected to "login" . maybe you're using different language.

**Comment by francescocassini** [comment] 2023-11-25 06:17
![Screenshot from 2023-11-25 07-05-44](https://github.com/AhmedElwerdany/blogger-image/assets/49899137/a3365687-61b4-45a0-9476-88efb3b33bfd)

Thank you very much for your response: I am not very familiar with node.js (I work in python), so I am having some difficulties.
Anyway I set headless = false in the src/index.ts file , deleted package-lock.json and make npm i image-blogger as you can see in the screenshot.
Reading your code I saw that there are some lines where it is checked if the blog language is "English". In my case it was "Italian": I set it to English, but the menu items still remain in Italian... very strange.

In the screenshot error message it's as if it doesn't find "div[data-tooltip="Insert image"]"... maybe because in the Italian version of Blogger it's called something else? The problem is that reading Blogger code with Developers tools under Chrome is not very easy. Is there any way to extract the source of the Blogger html page in an easier way and figure out what my tags are called?

Thanks for all the help you can give me!
Compliments for your code: I had had a similar idea, but I would never have known how to implement it, and on the Internet you are the only one who developed it because I looked for it everywhere.

**Comment by francescocassini** [comment] 2023-11-25 07:02
Another thing I've noticed, is that every time I run the program, when I go to restart chrome I'm no longer logged in and I have to re-login to every website. Is this normal?

**Comment by AhmedElwerdany** [comment] 2023-11-26 00:37
Hi,

I've tested the issue you reported on the latest versions of Chromium-based browsers and Firefox. I can confirm the issues you're experiencing. On Chromium, all logged-in sessions are lost, and on Firefox, there's an issue with disabling the CSP bypass as noted in this [Puppeteer issue](https://github.com/puppeteer/puppeteer/issues/5755).

I'm planning to test on older versions of these browsers to see if the issue persists there. I'll keep you updated on my findings.

Thank you for your patience and for bringing this to my attention.

**Comment by francescocassini** [comment] 2023-11-26 06:17
First, thank you for your help and quick responses.
I wanted to tell you that since this code would make my life much easier, I would also be willing to "fund" with (50/100 euro) any development of yours to fix the error and add an authentication check.
Can I contact you via email?

**Comment by AhmedElwerdany** [comment] 2023-11-26 17:39
Hi,

Firstly, I want to express my gratitude for your kind words and your generous offer. Your willingness to support the development of this project is greatly appreciated. However, it's not necessary to fund this development as I'm committed to providing solutions and improving the code for the benefit of all users. 

You can reach me via email at `infoalwerdany@gmail.com` for any further discussions or queries.

Now, let's address the issue you're facing. Here's the solution that works with the current version:

## Download the Older Version of Chromium
Navigate to the `.config` directory:
```shell
cd ~/.config
```
Download the older version of Chromium:
```shell
wget "https://www.googleapis.com/download/storage/v1/b/chromium-browser-snapshots/o/Linux_x64%2F962947%2Fchrome-linux.zip?generation=1643115368404678&alt=media" -q  --show-progress -O chrome_2f962947.zip
```
Unzip the downloaded file:
```shell
unzip chrome_2f962947.zip
```

## Login to Blogger
This will open the version of Chromium that we just downloaded:
```shell
cd chrome-linux; ./chrome
```
- Log in to your account.
- Ensure the language in Blogger is set to English. If it's not, change it from the same browser.
- Close the browser.

Run the following command and copy the result because you're going to need it in 'executablePath'. It should be `/home/{username}/.config/chrome-linux` where `{username}` is your username.
```shell
pwd
```

Now, use the following code:
```javascript
import Uploader from 'blogger-image'

try {
const uploader = new Uploader(
  'https://www.blogger.com/blog/post/edit/48547680384.../207376655....', // make sure that this post is belongs to the same user you just logged-in with.
  {
    ignoreDefaultArgs: true,
    userDataDir: '/home/{username}/.config/chromium',
    executablePath: '/home/{username}/.config/chrome-linux/chrome',
    args: ['--user-data-dir=/home/{username}/.config/chromium', '--headless']
  }
);
await uploader.init();

const result = await Promise.all([
  uploader.upload('./newtest.png'), // make sure to change the path with your image.
]);

console.log(result);
uploader.close();
}catch(err){
  console.log(err)
}
```

I hope this helps! Also, I'm excited to inform you that I'll be releasing a new version soon that will fix this issue. The `readme.md` file will be updated with the necessary instructions. Stay tuned!

**Comment by francescocassini** [comment] 2023-11-26 18:15
Hi Ahmed, what you said confirms that you are really a good person. I will test this solution as soon as possible by tomorrow.
After that I will contact you by email :)
Thank you very much great man!!!

**Comment by francescocassini** [comment] 2023-11-27 08:16
Okay, I tried your procedure and it seems to work. Unfortunately, however, the process crashes when the English language check is done.
In fact despite the fact that I have changed the blog language to English, Blogger continues to show the menus in Italian.
So I tried changing the language of the Google account (obviously under Chromium, i.e., the browser you had me download) to English.
Plus I removed the Italian language that was being seen as additional.
My Ubuntu system is English.
Despite all this, Blogger continues to show the menus in Italian and there is no setting to change this.

![Ahmed_changelanguage](https://github.com/AhmedElwerdany/blogger-image/assets/49899137/b5ce1731-5453-4a10-b91a-88d50e5e6289)

I'll try looking further, but from what I understand google removed the ability to change the blog language (the menu language) a few years ago.
Tomorrow I want to try to create an account that is from the start in English and see if the menus come in English.
In the meantime I will wait for the new version and consider me as your beta tester :)
Thank you for your patience Ahmed!!

Postscript: I'll write you by email, when I've defined some work that I've to do on my blog  ;)

**Comment by AhmedElwerdany** [comment] 2023-11-28 16:47
`version: 1.1.0`
- I have added support for Italian. 🇮🇹
- I have improved my error messages to be more clear and helpful.
- I have provided instructions to download the right browser for your system.

The package will have its own browser in version `2.0.0` with an option to use yours. So you won't need to download any browsers manually. Stay tuned for the update! 😊

**Comment by francescocassini** [comment] 2023-11-29 06:08
IT WORKS!!!!
Thanks a lot!!!
And I don't know if you've noticed that google has changed the way the image is "served".Check the URL you obtain from your program: before the filename there is a parameter "H96" indicating the height of the image. 
If you change that parameter, and make it 320 or 512, the image returned by Blogger will be of higher quality.
I will continue to use and testing.
Very well!!

**Comment by francescocassini** [comment] 2023-12-01 08:39
Sorry Ahmed for disturb you again.
I've made a fresh install on a server and this time I've got Chromium in english and I see Blogger menu in english.
Anyway I have got this error:
" throw new Error('Sorry, language is not supported\nlanguage: ' + language);
                  ^

Error: Sorry, language is not supported
language: en-GB
    at Uploader.init (file:///home/cirillo-server/Desktop/OPENROBO/blogger-image/node_modules/blogger-image/build/index.js:64:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///home/cirillo-server/Desktop/OPENROBO/blogger-image/index.js:18:1
"

Can I help you in some way?
Thanks alot

**Closed** 2023-12-01 15:07 UTC
